config/routes.rb
Rails.application.routes.draw do
	root to: 'posts#index'

  	devise_for :users 
	
	resources :posts do
		resources :comments, only: [:create, :new, :edit, :update, :destroy]
		
	end

	resources :stocks, only: [:show, :list, :new, :create] do
    	member do
    	  post 'add_to_watchlist'
    	  delete 'remove_from_watchlist'
    	end
  	end

	# get "posts/stocks/:id" => "stocks#show"
	get '/watchlist' => "stocks#list"
	# post '/stocks/add_to_watchlist/:id' => 'stocks#add_to_watchlist'
 #    delete '/stocks/:id/remove_from_watchlist' => 'stocks#remove_from_watchlist'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true
	
	belongs_to :user, optional: true
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :ticker, :body, presence: true
	
	belongs_to :user, optional: true
	has_many :comments, dependent: :destroy
end

app/models/stock.rb
class Stock < ApplicationRecord
	validates :ticker, presence: true
	
	has_many :watchlists
	has_many :users, through: :watchlists
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #:omniauthable, :omniauth_providers => [:google]

   #  def self.from_omniauth(auth)
   #  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
   #      	user.provider = auth.provider
   #      	user.uid = auth.uid
   #      	user.email = auth.info.email
   #      	user.password = Devise.friendly_token[0,20]
   #    	end
  	# end

    has_many :watchlists
    has_many :stocks, through: :watchlists


    has_many :posts
    has_many :comments
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord

	belongs_to :stock
	belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# include Pundit
	protect_from_forgery with: :exception

	before_action :authenticate_user!, except: [:index,:show]

	rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record
	rescue_from NoMethodError, with: :no_method_error

	private
  	def couldnt_find_record
    	redirect_to root_url, notice: "That stock doesn't exist??"
  	end

  	def no_method_error
    redirect_to root_url, notice: "Something doesn't exist"
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params.merge(user: current_user))
		if @comment.save
			flash[:notice] = "Comment Added"
			redirect_to post_path(@post)
		else
			flash[:alert] = "Comment did not save"
			redirect_to post_path(@post)
		end
	end
  	def new
  		@post = Post.find(params[:post_id])
  		@comment = Comment.new()
  	end

 	def edit
  		@post = Post.find(params[:post_id])
  		@comment = Comment.find(params[:id])
  	end
  	def update
  		@post = Post.find(params[:post_id])
  		@comment = @post.comments.find(params[:id])
      if @comment.user == current_user
  		  if @comment.update(comment_params)
  			 flash[:notice] = "Edit Successful"
  			 redirect_to post_path(@post)
  		  else
  			 flash[:alert] = "Edit did not Save"
  			 redirect_to post_path(@post)
  		  end
      else
        flash[:alert] = "You can't edit another persons comment"
        redirect_to root_path
      end
  	end

  	def destroy
  		@post = Post.find(params[:post_id])
  		@comment = @post.comments.find(params[:id])
      if @comment.user == current_user
  		  if @comment.destroy
  		  	flash[:notice] = "Comment Removed"
  		  	redirect_to post_path(@post)
  		  else
  		  	flash[:alert] = "Comment could not be Removed"
  		  	redirect_to post_path(@post)
  		  end
      else
        flash[:alert] = "Cant delete comments that are not your own"
        redirect_to root_path
      end
  	end

  	private
  		def comment_params
  			params.require(:comment).permit(:content)
  		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,execpt: [:index, :show]

  # after_action 
  # after_action 
  def index
  	@posts = Post.all.order(:created_at).reverse
    @stocks = Stock.all
  end

  def create
  	# 
    @post = Post.new(post_params.merge(user: current_user))
    @post.ticker.upcase!

    @stocks = Stock.all
    @new_stock = Stock.new(ticker: @post.ticker, price: 0.00)

    if @stocks.any? {|h| h[:ticker] == @post.ticker}
      if @post.save
        flash[:notice] = "New Post Created"
        redirect_to root_path
      else
        flash[:alert] = "Error Post did not save"
        redirect_to root_path
      end
    else
      @new_stock.save
      if @post.save
        flash[:notice] = "New Post Created"
        redirect_to root_path
      else
        flash[:alert] = "Error Post did not save"
        redirect_to root_path
      end
  	end
  end

  def new
  	@post = Post.new
  end

  def edit 
  	@post = Post.find(params[:id])
  end

  def show
  	@post = Post.find(params[:id])
    @stock = Stock.find_by(ticker: "#{@post.ticker}")
  	@comments = @post.comments.all.order(:updated_at).reverse
  end

  def update
  	@post = Post.find(params[:id])
    # authorize @post
   if @post.user == current_user
  	   if @post.update(post_params)
  		  flash[:notice] = "Edit Successful"
  		  redirect_to post_path(@post)
  	   else
  		  flash[:alert] = "Edit did not save!"
  		  redirect_to post_path(@post)
  	   end
   else
      flash[:alert] = "Sorry you are not allowed to edit this"
      redirect_to root_path
   end
  end

  def destroy
  	@post = Post.find(params[:id])
    if @post.user == current_user
  	  if @post.destroy
  	 	  flash[:notice] = "Post Destroyed"
  		  redirect_to root_path
  	  else
  		  flash[:alert] = "Post did not delete"
  		  redirect_to root_path
  	  end
    else
      flash[:alert] = "You are not allowed to delete this"
      redirect_to edit_post_path(@post)
    end
  end

  private
  	def post_params
  		params.require(:post).permit(:ticker,:body)
  	end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

	def show
		@stock = Stock.find(params[:id])
	end

	def list
		@my_list = Watchlist.where(user: current_user)
		@my_stocks = []
		@my_list.each do |x|

			@my_stocks.push(x.stock_id)

		end
	end

	def new
		@stock = Stock.new()
	end

	def create
		#stuff to search through
		@all_stocks = Stock.all
		@my_list = Watchlist.where(user: current_user)
		#new Stock 
		@stock = Stock.new(stock_params)
		@stock.ticker.upcase!
		#exsisting Stock
		@db_stock = Stock.find_by(ticker: @stock.ticker)
		# if in database
		if @all_stocks.any? {|h| h[:ticker] == @stock.ticker}
			#if in watchlist
			if @my_list.any? {|h| h[:stock_id] == @db_stock.id}
				#in both
				flash[:notice] = "That stock is already in your watchlist"
				redirect_to watchlist_path
			else
				# in database, not in watchlist
				@db_stock.ticker.upcase!
				@db_stock.update(stock_params)
				@db_stock.watchlists.create!(user: current_user)
				flash[:notice] = "#{@db_stock.ticker} added to list"
				redirect_to watchlist_path
			end
		else
			#not in either
			@stock.save
			@stock.watchlists.create!(user: current_user)
			flash[:notice] = "#{@stock.ticker} added to list"
			redirect_to watchlist_path
		end
	end

	def add_to_watchlist
		@my_stock = Stock.find(params[:id])
		@my_list = Watchlist.where(user: current_user)

		if @my_list.any? {|h| h[:stock_id] == @my_stock.id}
			flash[:notice] = "You are already watching this stock"
			redirect_to root_path
		else
			@my_stock.watchlists.create!(user: current_user)
			flash[:notice] = "#{@my_stock.ticker} added to watchlist"
			redirect_to watchlist_path
		end
  	end

  	def remove_from_watchlist
		@stock = Stock.find(params[:id])

   	if Watchlist.find_by(user: current_user, stock_id: params[:id]).destroy
   		flash[:alert] = "Stock Removed from watchlist"
   		redirect_to watchlist_path
   	else
   		flash[:alert] = "Could not remove stock"
   		redirect_to watchlist_path
   	end

  	end

  	private
  		def stock_params
  			params.require(:stock).permit(:ticker,:price)
  		end

end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Edit your Comment</h1>

<div class="form">
	<%= form_for [@post,@comment] do |f| %>

		<%= f.label :content%><br>
		<%= f.text_area  :content,required: true%><br>

		<%= f.submit %>
		<%end%>
		<%= form_for [@post,@comment], method: :delete do |f| %>
			<%= f.submit "Delete Comment?",class: "destroy"%>
		<%end%>
</div>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<div class="form">
	<%= form_for [@post,@comment] do |f| %>
		
		<%= f.label "Write Your Comment"%><br>
		<%= f.text_field  :content,required: true%><br>

		<%= f.submit %>
	<%end%>
 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockCraft</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
  	<h1><%=link_to "StockCraft", root_path %></h1>
    </header>
    <nav>
      <div class="logLinks">
          <%if !current_user%>
            <%= link_to "Sign In", new_user_session_path%>
            <%= link_to "Sign Up", new_user_registration_path%>
          <%else%>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
          <%end%>
      </div>
      <div class="routeLinks">
  	   <%= link_to "Make a Post", new_post_path %>
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  	   <%= link_to "My Watchlist", watchlist_path %>
      </div>
    </nav>
    <%flash.each do |type, messege|%>
      <p class="<%=type%>"><%=messege%></p>
    <%end%>
    <div class="boxy">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit your Post</h2>

<div class="form">
	<%= form_for @post do |f| %>
		<%= f.label "Stock Ticker"%><br>
		<%= f.text_field  :ticker, required: true,readonly: true%><br>

		<%= f.label " "%><br>
		<%= f.text_area  :body,required: true%><br>

		<%= f.submit %>
		<%end%>
		<%= form_for @post, method: :delete do |f| %>
			<%= f.submit "Delete Post?",class: "destroy"%>
		<%end%>
</div>

app/views/posts/index.html.erb
<div class="feed">

<% @posts.each do |post|%>
<div class="post">

	<div class="ticker">
		<h4>
			<a href='/stocks/<%= Stock.find_by(ticker: "#{post.ticker}").id %>'>
				<%= post.ticker %>
			</a>
		</h4>
		<span class="price">
				<%= Stock.find_by(ticker: "#{post.ticker}").price %>
		</span>
	</div>
	<div class="stuff">
			<a href="/posts/<%=post.id%>">
				
					<p><%= post.body %></p>
			</a>
	</div>
</div>
<%end%>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>


<div class="form">
	<%= form_for @post do |f| %>
		<%= f.label "Stock Ticker"%><br>
		<%= f.text_field  :ticker, required: true%><br>

		<%= f.label " "%><br>
		<%= f.text_area  :body, required: true%><br>

		<%= f.submit %>
		<%end%>
</div>

app/views/posts/show.html.erb
<div class="post">
	<h4>
		<a href="/stocks/<%= @stock.id%>">
			<%= Stock.find_by(ticker: "#{@post.ticker}").ticker %>
		</a>&nbsp;&nbsp;&nbsp;
	  	<span class="price"><%=@stock.price%></span>
	  	<span class="add"><%=link_to " ★",add_to_watchlist_stock_path(@stock),method: :post%></span>
	</h4>
	<p><%= @post.body %></p>
</div>

<div class="postLinks">
	<%if current_user == @post.user%>
		<%= link_to "Edit Post", edit_post_path(@post)%>
		<%= link_to "Add Comment", new_post_comment_path(@post)%>
	<%else%>
		<%= link_to "Add Comment", new_post_comment_path(@post)%>
	<%end%>

</div>

<% @comments.each do |comm| %>
<div class="comments">
	<% if comm.user == current_user %>
		<p><%= comm.content %></p>
		<span class="timestamp"><%= comm.updated_at %></span><br>
		<%= link_to "Edit Comment", edit_post_comment_path(@post,comm)%>
	<%else%>
		<p><%= comm.content %></p>
		<span class="timestamp"><%= comm.updated_at %></span>

	<%end%>
</div>
<%end%>

app/views/stocks/list.html.erb
<div class="watchArea">
	<div class="watchHead">
		<h2>My Watchist</h2>
		<h3><%= link_to "Add a stock to the watchlist", new_stock_path %></h3>
	</div>




	<div class="watchist">
<% @my_stocks.each do |s|%>
		<div class="stockBox">
			<p><%= link_to Stock.find(s).ticker, stock_path(s)%> &nbsp;&nbsp; <%=Stock.find(s).price%></p>
			<%= link_to "Remove", remove_from_watchlist_stock_path(s), method: :delete %>
		</div>
<%end%>
	</div>
</div>

app/views/stocks/new.html.erb
<h2>Add a Stock</h2>

<div class="form">
	<%= form_for @stock do |f| %>
		<%= f.label "Ticker Symbol"%><br>
		<%= f.text_field :ticker%><br>

		<%= f.label "Price"%><br>
		<%= f.number_field :price, step: :any%><br>
		
		<%= f.submit %>
	<%end%>
</div>

app/views/stocks/show.html.erb
<div class="stockShow">
	<h4>
		<%= @stock.ticker %>
		<span class="add"><%=link_to " ★",add_to_watchlist_stock_path(@stock),method: :post%></span>
	</h4>
	<p><%= @stock.price %></p>
	<img src="" alt="Awesome Stock Chart Would go here">
	<p>Additional companay data Would go here</p>
</div>